prototype an example-based approach to explaining the rewrites
jam1garner/edition-guide pull request #1
Opened 2021-07-06 16:33 UTC by nikomatsakis

2021-07-06 19:54 UTC, rylev requested changes
This is the right direction, but I think we're missing key details.

2021-07-06 19:54 UTC, rylev commented on src/rust-2021/prelude.md
> +trait Foo {
The use of `Foo` for both the trait here and the struct above is confusing. Can we use different names?

2021-07-06 19:54 UTC, rylev commented on src/rust-2021/prelude.md
> +Many types define their own inherent methods with the name `from_iter`:
Can we establish that there is a method `from_iter` on the `FromIter` trait. I think we're requiring the reader to piece too much together here.

2021-07-06 19:54 UTC, rylev commented on src/rust-2021/prelude.md
> +Calls like `Foo::from_iter` cannot be confused with calls to `<Foo as FromIter>::from_iter`, because inherent methods take precedence over trait methods.
I think also we should connect the dots for the reader. Something like: "rewriting method calls to use fully qualified syntax ensures that the inherent method will be called".

2021-07-06 19:54 UTC, rylev commented on src/rust-2021/prelude.md
> +  f.into_iter();
Why would `into_iter` mean `FromIter::into_iter`? Does `Foo` implement `FromIter`?

2021-07-06 19:54 UTC, rylev commented on src/rust-2021/prelude.md
> +In these cases, the lint will sometimes rewrite to introduce additional dereferences or otherwise clarify the type of the method receiver. This ensures that the `dyn Trait` method is chosen, versus t
Why does the dereference make the trait object method call unambiguous?

2021-07-07 00:51 UTC, nikomatsakis commented
@rylev these are good comments but I don't know if I'll have time to follow up on them! maybe @jam1garner can land this and then we can continue on the main PR?

2021-07-09 04:05 UTC, merged